version: 2
updates:
  # Check for npm dependency updates
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly

  # Check for GitHub Actions dependency updates
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
